{
"title": "This Site",
"date": "2018-02-11T12:41:05-05:00",
"tags": ["html","javascript","HUGO","CircleCI","GitHub","git","golang"],
"description": "This site itself is a static HTML/JS site generated by <a href=\"https://gohugo.io/\">HUGO</a> via a CircleCI's Continuous Delivery <a href=\"https://circleci.com/gh/eddiewebb/json-resume\">pipelines</a> from a github <a href=\"https://github.com/eddiewebb/json-resume\">repository</a>. <img src=\"https://circleci.com/gh/eddiewebb/json-resume.svg?style=svg\" alt=\"CircleCI Status Badge\"/>",
"contributionUrl": "https://github.com/eddiewebb/json-resume",
"image": "/img/circleci-workflow.png"
}

<p>This site itself is a static HTML/JS site generated by <a href="https://gohugo.io/">HUGO</a> via a CircleCI's Continuous Delivery <a href="https://circleci.com/gh/eddiewebb/json-resume">pipelines</a> from a github <a href="https://github.com/eddiewebb/json-resume">repository</a>. <img src="https://circleci.com/gh/eddiewebb/json-resume.svg?style=svg" alt="CircleCI Status Badge"/></p>

<p>Originally created as a simple HTML/CSS site hosted statically I immediately annoyed at the copy/pasting required to format my various projects, experience etc in the same formatting. I at first used Handlebars to do some simple templating backed by JSON files.  This worked well but since everything was rendered on the client side it negatively impacted searchability by robots like Google.</p>

<p>After comparing many static site generators I landed on HUGO. HUGO's templating language uses <a href="https://golang.org">go</a> for the logic, and includes a live server for local development. This site's details (experience, skills, personal info) are all still fed by a collection of JSON data files that decouples presentation from content, but is only generated once as part of a CircleCI workflow.</p>
