baseURL = "https://edwardawebb.com/"
languageCode = "en-us"
title = "Eddie Webb"
theme = "resume"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

[params]
    firstName = "Eddie"
    lastName = "Webb"
    address = "Rollinsford, NH"
    email = "OlliTech@gmail.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "key"





[params.google.analytics]
    trackerID = "UA-28342049-2"
