baseURL = "https://edwardawebb.com/"
languageCode = "en-us"
title = "Eddie Webbinaro"
theme = "resume"
enableGitInfo = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
    style = "tango"




[taxonomies]
    tag = "tags"
    "ADV Tags" = "advtags"


[params]
    firstName = "Eddie"
    lastName = "Webbinaro"
    profileImage = "img/TechChat.webp"
    phone = "603-463-0447"
    contactNote = "Technology Sales Leader in CI, CD, and DevOps"
    address = "Peru, NY"
    email = "eddie@webbinaro.dev"
    description = "Eddie has over 15 years experience enabling agile, CI/CD and DevOps culture in the enterprise.  Previously the Director of Enterprise DevOps Platforms influencing culture and technology at a Fortune 100 company, Eddie now helps CircleCI customers of all sizes adopt the best technologies and practices on their DevOps journey."
    favicon = "images/favicon.ico"
    # what sections
    showQr = false
    showContact     = true

    # do you want to show git hash on page footer and link to repo? Add commit prefix here.
    gitCommitPrefix = "https://github.com/eddiewebb/json-resume/commit/"

    sections = ["skills","publications","creations","contributions","experience","education","blog"]

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"

#[[params.handles]]
#    name = "Twitter"
#    link = "https://twitter.com/edwardawebb/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"
    
[[params.handles]]
    name = "Bluesky"
    link = "https://bsky.app/profile/webbinaro.dev"
    icon = "bluesky"

#[[params.handles]]
#    name = "VCard"
#    link = "/Eddie_Webbinaro.vcf"
#    icon = "id-card fas"

[permalinks]
  publications = "/presentations/:title/"



[params.google.analytics]
    trackerID = "UA-28342049-2"


[outputs]
    home = ["HTML", "JSON"]
