baseURL = "https://edwardawebb.com/"
languageCode = "en-us"
title = "Eddie Webbinaro"
theme = "resume"
enableGitInfo = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
    style = "tango"




[taxonomies]
    tag = "tags"


[params]
    firstName = "Eddie"
    lastName = "Webbinaro"
    profileImage = "img/TechChat.webp"
    phone = "603-463-0447"
    contactNote = "DevTools Engineer and DevOps Culture advocate"
    address = "Peru, NY"
    email = "eddie@webb.dev"
    description = "Eddie has over a decade of experience enabling agile, CI/CD and DevOps culture in the enterprise.  Previously the Director of Enterprise DevOps Platforms influencing culture and technology at a Fortune 100 company, Eddie now helps CircleCI customers of all sizes adopt the best technologies and practices on their DevOps journey."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    publicationsAlternateName = "Presentations"
    showExperience = true
    showEducation = true
    showBlog      = true
    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit prefix here.
    gitCommitPrefix = "https://github.com/eddiewebb/json-resume/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/edwardawebb/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Sourcerer"
    link = "https://sourcerer.io/eddiewebb/"
    icon = "osi"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"

[permalinks]
  publications = "/presentations/:title/"



[params.google.analytics]
    trackerID = "UA-28342049-2"


[outputs]
  home = ["HTML", "JSON"]
